system: test
test:
  archive:
    bandwidth: 1
    mount: /Users/DGhoshal/workdir/uda/css/wfm/tests/_tmp/archive
    persist: LongTerm
  burst:
    bandwidth: 1600
    mount: /Users/DGhoshal/workdir/uda/css/wfm/tests/_tmp/burst
    persist: None
  scratch:
    bandwidth: 700
    mount: /Users/DGhoshal/workdir/uda/css/wfm/tests/_tmp/scratch
    persist: ShortTerm
